[tox]
envlist =
    {py311,py312,py313,py314},
    lint,

skip_missing_interpreters = True

[testenv]
usedevelop = True
extras =
    test

basepython:
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

commands =
    pytest --cov=plonecli tests {posargs}

setenv =
    PYTHONPATH = {toxinidir}

passenv =
    VERBOSE
    PLONECLI_TEMPLATES_REPO_URL
    PLONECLI_TEMPLATES_BRANCH
    PLONECLI_TEMPLATES_DIR

deps =
    pytest
    pytest-cov

[testenv:lint]
basepython = python3.13
skip_install = true
deps =
    ruff
commands =
    ruff check {toxinidir}/plonecli {toxinidir}/tests
    ruff format --check {toxinidir}/plonecli {toxinidir}/tests
